[package]
name = "hstring"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.83"
cty = "0.2.2"

[build-dependencies]
bindgen = {}
cc = {}

[lib]